### ISSUE TITLE
Codecov

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/swift-client#7]
See https://github.com/codecov/example-swift for an example

**Comment by ItsANameToo** [comment]
@faustbrian can you enable codecov for this repo?

**Comment by ItsANameToo** [comment]
Never mind, seems that you already enabled it as the badge now shows coverage after latest travis build :)

**Comment by faustbrian** [comment]
Just takes a moment for them to receive and process the coverage after travis runs.
